name: Світлобот Дударків

on:
  schedule:
    # Щодня о 7:00 Київського часу (UTC+2/3)
    - cron: "0 4 * * *"  # UTC = Київ - 3 години
    # Перевірка каналу кожні 5 хв
    - cron: "*/5 * * * *"
  workflow_dispatch:  # ручний запуск

jobs:
  run-parser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Встановити Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Встановити залежності
        run: pip install --upgrade pip && pip install requests python-telegram-bot beautifulsoup4

      - name: Запустити парсер
        run: python parser.py
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
